# DO NOT DELETE

Autoencoder.o: global.hpp timing.h NeuralStruct.hpp imageio.hpp eigen.hpp
Autoencoder.o: matops.hpp Autoencoder.hpp
NeuralStruct.o: NeuralStruct.hpp global.hpp timing.h
build.o: global.hpp timing.h imageio.hpp eigen.hpp Autoencoder.hpp
build.o: NeuralStruct.hpp matops.hpp build.hpp
check_gradient.o: global.hpp timing.h Autoencoder.hpp eigen.hpp prng.hpp
check_gradient.o: check_gradient.hpp
denoise.o: global.hpp timing.h build.hpp Autoencoder.hpp eigen.hpp
denoise.o: NeuralStruct.hpp
global.o: global.hpp timing.h
imageio.o: global.hpp timing.h io_png.h prng.hpp imageio.hpp eigen.hpp bm3d
io_png.o: io_png.h
matops.o: global.hpp timing.h prng.hpp tanh.hpp matops.hpp
timing.o: timing.h
train.o: global.hpp timing.h build.hpp Autoencoder.hpp eigen.hpp
train.o: check_gradient.hpp
eigen.hpp: eigen
bm3d/bm3d.cpp: bm3d
bm3d/utilities.cpp: bm3d
bm3d/lib_transforms.cpp: bm3d
bm3d/mt19937ar.c: bm3d
